# Generated by Django 3.0.5 on 2020-09-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='product type')),
            ],
            options={
                'verbose_name': 'Coffee Machine product type',
                'verbose_name_plural': 'Coffee Machine product types',
            },
        ),
        migrations.CreateModel(
            name='CoffeeFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='coffee flavor')),
            ],
            options={
                'verbose_name': 'Coffee Flavor',
                'verbose_name_plural': 'Coffee Flavors',
            },
        ),
        migrations.CreateModel(
            name='CPProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='product type')),
            ],
            options={
                'verbose_name': 'Coffee Pot product type',
                'verbose_name_plural': 'Coffee Pot product types',
            },
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='pack size')),
            ],
            options={
                'verbose_name': 'Coffee Flavor',
                'verbose_name_plural': 'Coffee Flavors',
            },
        ),
        migrations.CreateModel(
            name='CoffeePot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=7)),
                ('coffee_flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffee_flavor', to='CoffeeAndPods.CoffeeFlavor')),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_size', to='CoffeeAndPods.PackSize')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_type', to='CoffeeAndPods.CPProductType')),
            ],
            options={
                'verbose_name': 'coffee Pot',
                'verbose_name_plural': 'coffee Pots',
            },
        ),
        migrations.CreateModel(
            name='CoffeeMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_line_compatible', models.BooleanField(default=False, verbose_name='water_line_compatible')),
                ('sku', models.CharField(max_length=7)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_type', to='CoffeeAndPods.CMProductType')),
            ],
            options={
                'verbose_name': 'Coffee Machine',
                'verbose_name_plural': 'Coffee Machines',
            },
        ),
    ]
